sonar.projectKey=fayrus_canopus
sonar.organization=fayrus

sonar.sources=canopus
sonar.exclusions=docs/**,venv/**,canopus.egg-info/**

sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
